### ISSUE TITLE
Todo's for you.

### ISSUE THREAD

**Issue by shumailxyz** [BurhanMohyuddin/burhanmohyuddin.github.io#1]
- [x] fix class naming. `Container` is wrong with capital C. it's with small c.
- [x] fix alignment of top subheading and heading
- [x] fix alignment of all 3 buttons in a way that it doesn't mess up
- [x] get rid of horizontal scrollbar and understand why it's happening
- [x] Check alignment of bottom buttons and fix them
- [x] Style the bottom buttons correctly. Currently you are using `p` & `& emsp` [(line#86)](https://github.com/BurhanMohyuddin/burhanmohyuddin.github.io/blob/master/index.html#L86) to style them which is wrong. Use bootstrap cols to style them.
- [x] Set the names for `id` of elements properly. For example, `multiCollapseExample1` doesn't make any sense. Do check the snipped of code after copying it and change it wherever required.
- [ ] Fix it all for mobile. It's not responsive at all at the moment.

**Comment by shumailxyz** [comment]
Also remove any inline styling. for example, on line 13 you have `style="background-color: #ffffff;"`

move it into `style.css`
